import "server-only";

import {
  AlignmentType,
  Document,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { PDFFont, PDFPage, RGB } from "pdf-lib";

import { brand } from "@/lib/brand";
import type { ResumeContent } from "@/lib/resumes/resume-content";

type ResumeTemplateInput = {
  contextLine?: string | null;
  displayName?: string | null;
  resume: ResumeContent;
};

type CoverLetterTemplateInput = {
  contextLine: string;
  coverLetter: string;
};

const pageWidth = 612;
const pageHeight = 792;
const marginX = 58;
const marginTop = 54;
const marginBottom = 54;
const contentWidth = pageWidth - marginX * 2;
const navy = rgb(0.05, 0.09, 0.16);
const taupe = rgb(0.47, 0.4, 0.32);
const rule = rgb(0.83, 0.77, 0.68);

export async function buildAtsResumePdf(input: ResumeTemplateInput) {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const document = createPdfLayout({ bold, pdf, regular });
  const headline = formatResumeHeadline(input.resume.headline);

  drawTextBlock(document, input.displayName ?? input.resume.headline, {
    font: bold,
    size: 18,
  });

  if (input.displayName) {
    drawTextBlock(document, headline, {
      color: taupe,
      font: regular,
      lineGap: 3,
      size: 10.5,
    });
  }

  const contactLine = formatContactLine(input.resume);
  if (contactLine) {
    drawTextBlock(document, contactLine, {
      color: taupe,
      font: regular,
      lineGap: 3,
      size: 9.2,
    });
  }

  if (input.contextLine) {
    drawTextBlock(document, input.contextLine, {
      color: taupe,
      font: regular,
      lineGap: 3,
      size: 9.5,
    });
  }

  drawRule(document);
  drawSection(document, "Professional Summary", [input.resume.summary]);
  drawSection(document, "Core Skills", [formatSkills(input.resume.skills)]);
  drawSelectedHighlights(document, input.resume);
  drawExperience(document, input.resume);
  drawEducation(document, input.resume);
  drawCertifications(document, input.resume);

  return pdf.save();
}

export async function buildAtsResumeDocx(input: ResumeTemplateInput) {
  const headline = formatResumeHeadline(input.resume.headline);
  const children: Paragraph[] = [
    docxParagraph(input.displayName ?? input.resume.headline, {
      bold: true,
      color: "0D1728",
      size: 30,
      spacingAfter: 80,
    }),
  ];

  if (input.displayName) {
    children.push(
      docxParagraph(headline, {
        color: "6F6252",
        size: 21,
        spacingAfter: 60,
      }),
    );
  }

  const contactLine = formatContactLine(input.resume);
  if (contactLine) {
    children.push(
      docxParagraph(contactLine, {
        color: "6F6252",
        size: 18,
        spacingAfter: 60,
      }),
    );
  }

  if (input.contextLine) {
    children.push(
      docxParagraph(input.contextLine, {
        color: "6F6252",
        size: 19,
        spacingAfter: 140,
      }),
    );
  }

  children.push(
    docxSectionHeading("Professional Summary"),
    docxParagraph(input.resume.summary, { spacingAfter: 160 }),
    docxSectionHeading("Core Skills"),
    docxParagraph(formatSkills(input.resume.skills), { spacingAfter: 160 }),
    ...buildDocxSelectedHighlights(input.resume),
    ...buildDocxExperience(input.resume),
    ...buildDocxEducation(input.resume),
    ...buildDocxCertifications(input.resume),
  );

  return Packer.toBuffer(createDocx(children, "ATS resume"));
}

export async function buildCoverLetterPdf(input: CoverLetterTemplateInput) {
  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const document = createPdfLayout({ bold, pdf, regular });

  drawTextBlock(document, input.contextLine, { font: bold, size: 16 });
  drawTextBlock(document, `Generated by ${brand.name} for review`, {
    color: taupe,
    font: regular,
    size: 9.5,
  });
  drawRule(document);
  drawTextBlock(document, input.coverLetter, {
    font: regular,
    lineGap: 5,
    size: 10.5,
  });

  return pdf.save();
}

export async function buildCoverLetterDocx(input: CoverLetterTemplateInput) {
  return Packer.toBuffer(
    createDocx(
      [
        docxParagraph(input.contextLine, {
          bold: true,
          color: "0D1728",
          size: 28,
          spacingAfter: 90,
        }),
        docxParagraph(`Generated by ${brand.name} for review`, {
          color: "6F6252",
          size: 19,
          spacingAfter: 220,
        }),
        ...input.coverLetter
          .split(/\n{2,}/)
          .map((paragraph) =>
            docxParagraph(paragraph.trim(), {
              spacingAfter: 170,
            }),
          ),
      ],
      "Cover letter",
    ),
  );
}

type PdfLayout = {
  bold: PDFFont;
  cursorY: number;
  page: PDFPage;
  pdf: PDFDocument;
  regular: PDFFont;
};

function createPdfLayout({
  bold,
  pdf,
  regular,
}: {
  bold: PDFFont;
  pdf: PDFDocument;
  regular: PDFFont;
}): PdfLayout {
  return {
    bold,
    cursorY: pageHeight - marginTop,
    page: pdf.addPage([pageWidth, pageHeight]),
    pdf,
    regular,
  };
}

function drawSection(document: PdfLayout, title: string, lines: string[]) {
  addVerticalSpace(document, 10);
  drawTextBlock(document, title.toUpperCase(), {
    color: navy,
    font: document.bold,
    lineGap: 2,
    size: 10,
  });
  addVerticalSpace(document, 3);

  for (const line of lines.filter(Boolean)) {
    drawTextBlock(document, line, {
      font: document.regular,
      lineGap: 4,
      size: 10.2,
    });
    addVerticalSpace(document, 4);
  }
}

function drawExperience(document: PdfLayout, resume: ResumeContent) {
  const sections = resume.experienceSections ?? [];

  if (sections.length === 0) {
    return;
  }

  addVerticalSpace(document, 10);
  drawTextBlock(document, "PROFESSIONAL EXPERIENCE", {
    color: navy,
    font: document.bold,
    lineGap: 2,
    size: 10,
  });
  addVerticalSpace(document, 3);

  for (const section of sections) {
    const heading = [section.roleTitle, section.company].filter(Boolean).join(", ");
    drawTextBlock(document, heading, {
      font: document.bold,
      lineGap: 3,
      size: 10.4,
    });
    const meta = [section.location, section.dates].filter(Boolean).join(" | ");
    if (meta) {
      drawTextBlock(document, meta, {
        color: taupe,
        font: document.regular,
        lineGap: 3,
        size: 9.3,
      });
    }
    for (const bullet of section.bullets) {
      drawTextBlock(document, `- ${bullet}`, {
        font: document.regular,
        lineGap: 4,
        size: 10.2,
      });
    }
    addVerticalSpace(document, 5);
  }
}

function drawSelectedHighlights(document: PdfLayout, resume: ResumeContent) {
  const bullets = resume.experienceBullets.filter(Boolean).slice(0, 6);

  if (bullets.length === 0) {
    return;
  }

  drawSection(
    document,
    "Selected Highlights",
    bullets.map((bullet) => `- ${bullet}`),
  );
}

function drawEducation(document: PdfLayout, resume: ResumeContent) {
  const lines = resume.education.map(formatEducationLine).filter(Boolean);

  if (lines.length === 0) {
    return;
  }

  drawSection(document, "Education", lines);
}

function drawCertifications(document: PdfLayout, resume: ResumeContent) {
  const lines = resume.certifications.map(formatCertificationLine).filter(Boolean);

  if (lines.length === 0) {
    return;
  }

  drawSection(document, "Certifications", lines);
}

function buildDocxExperience(resume: ResumeContent) {
  const sections = resume.experienceSections ?? [];

  if (sections.length === 0) {
    return [];
  }

  return [
    docxSectionHeading("Professional Experience"),
    ...sections.flatMap((section) => {
      const heading = [section.roleTitle, section.company].filter(Boolean).join(", ");
      const meta = [section.location, section.dates].filter(Boolean).join(" | ");
      return [
        docxParagraph(heading, {
          bold: true,
          spacingAfter: 40,
          spacingBefore: 80,
        }),
        ...(meta
          ? [
              docxParagraph(meta, {
                color: "6F6252",
                size: 19,
                spacingAfter: 60,
              }),
            ]
          : []),
        ...section.bullets.map((bullet) =>
          docxParagraph(bullet, {
            bullet: true,
            spacingAfter: 70,
          }),
        ),
      ];
    }),
  ];
}

function buildDocxSelectedHighlights(resume: ResumeContent) {
  const bullets = resume.experienceBullets.filter(Boolean).slice(0, 6);

  if (bullets.length === 0) {
    return [];
  }

  return [
    docxSectionHeading("Selected Highlights"),
    ...bullets.map((bullet) =>
      docxParagraph(bullet, {
        bullet: true,
        spacingAfter: 70,
      }),
    ),
  ];
}

function buildDocxEducation(resume: ResumeContent) {
  const lines = resume.education.map(formatEducationLine).filter(Boolean);

  if (lines.length === 0) {
    return [];
  }

  return [
    docxSectionHeading("Education"),
    ...lines.map((line) =>
      docxParagraph(line, {
        spacingAfter: 70,
      }),
    ),
  ];
}

function buildDocxCertifications(resume: ResumeContent) {
  const lines = resume.certifications.map(formatCertificationLine).filter(Boolean);

  if (lines.length === 0) {
    return [];
  }

  return [
    docxSectionHeading("Certifications"),
    ...lines.map((line) =>
      docxParagraph(line, {
        spacingAfter: 70,
      }),
    ),
  ];
}

function formatEducationLine(item: ResumeContent["education"][number]) {
  return [item.credential, item.institution, item.location, item.dates].filter(Boolean).join(" | ");
}

function formatCertificationLine(item: ResumeContent["certifications"][number]) {
  return [item.name, item.issuer, item.date].filter(Boolean).join(" | ");
}

function formatResumeHeadline(headline: string) {
  const normalized = headline.replace(/\s*\|\s*/g, " / ").replace(/\s+/g, " ").trim();
  const segments = normalized.split(/\s+\/\s+/).filter(Boolean);

  if (segments.length <= 2) {
    return normalized;
  }

  return segments.slice(0, 2).join(" / ");
}

function formatSkills(skills: string[]) {
  return skills.filter(Boolean).join(", ");
}

function formatContactLine(resume: ResumeContent) {
  const contact = resume.contact;
  return [contact.email, contact.phone, contact.linkedin, contact.website, contact.location]
    .filter(Boolean)
    .join(" | ");
}

function drawTextBlock(
  document: PdfLayout,
  text: string,
  {
    color = navy,
    font,
    lineGap = 4,
    size,
    x = marginX,
  }: {
    color?: RGB;
    font: PDFFont;
    lineGap?: number;
    size: number;
    x?: number;
  },
) {
  const lines = wrapText(text, font, size, contentWidth);

  for (const line of lines) {
    ensureSpace(document, size + lineGap);

    document.page.drawText(line, {
      color,
      font,
      size,
      x,
      y: document.cursorY,
    });
    document.cursorY -= size + lineGap;
  }
}

function drawRule(document: PdfLayout) {
  addVerticalSpace(document, 8);
  ensureSpace(document, 12);
  document.page.drawLine({
    color: rule,
    end: { x: pageWidth - marginX, y: document.cursorY },
    start: { x: marginX, y: document.cursorY },
    thickness: 0.8,
  });
  document.cursorY -= 10;
}

function addVerticalSpace(document: PdfLayout, space: number) {
  ensureSpace(document, space);
  document.cursorY -= space;
}

function ensureSpace(document: PdfLayout, requiredHeight: number) {
  if (document.cursorY - requiredHeight >= marginBottom) {
    return;
  }

  document.page = document.pdf.addPage([pageWidth, pageHeight]);
  document.cursorY = pageHeight - marginTop;
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number) {
  return text
    .split("\n")
    .flatMap((paragraph) => {
      const words = paragraph
        .trim()
        .split(/\s+/)
        .filter(Boolean)
        .flatMap((word) => splitLongWord(word, font, size, maxWidth));
      const lines: string[] = [];
      let currentLine = "";

      for (const word of words) {
        const candidate = currentLine ? `${currentLine} ${word}` : word;

        if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
          currentLine = candidate;
          continue;
        }

        if (currentLine) {
          lines.push(currentLine);
        }
        currentLine = word;
      }

      if (currentLine) {
        lines.push(currentLine);
      }

      return lines.length > 0 ? lines : [""];
    });
}

function splitLongWord(word: string, font: PDFFont, size: number, maxWidth: number) {
  if (font.widthOfTextAtSize(word, size) <= maxWidth) {
    return [word];
  }

  const segments: string[] = [];
  let segment = "";

  for (const character of word) {
    const candidate = `${segment}${character}`;

    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      segment = candidate;
      continue;
    }

    if (segment) {
      segments.push(segment);
    }
    segment = character;
  }

  if (segment) {
    segments.push(segment);
  }

  return segments;
}

function createDocx(children: Paragraph[], title: string) {
  return new Document({
    creator: brand.name,
    description: `${brand.name} standard ATS template`,
    sections: [
      {
        children,
        properties: {
          page: {
            margin: {
              bottom: 720,
              left: 720,
              right: 720,
              top: 720,
            },
          },
        },
      },
    ],
    title,
  });
}

function docxSectionHeading(text: string) {
  return docxParagraph(text.toUpperCase(), {
    bold: true,
    color: "0D1728",
    size: 20,
    spacingAfter: 60,
    spacingBefore: 120,
  });
}

function docxParagraph(
  text: string,
  {
    bold = false,
    bullet = false,
    color = "0D1728",
    size = 21,
    spacingAfter = 100,
    spacingBefore = 0,
  }: {
    bold?: boolean;
    bullet?: boolean;
    color?: string;
    size?: number;
    spacingAfter?: number;
    spacingBefore?: number;
  } = {},
) {
  return new Paragraph({
    alignment: AlignmentType.LEFT,
    bullet: bullet ? { level: 0 } : undefined,
    children: [
      new TextRun({
        bold,
        color,
        font: "Arial",
        size,
        text,
      }),
    ],
    spacing: {
      after: spacingAfter,
      before: spacingBefore,
      line: 276,
    },
  });
}
